// Shared navigation and footer. Keep the markup and behavior in this file.
(function(){
const header=document.getElementById('site-header');
const footer=document.getElementById('site-footer');
const page=document.body.dataset.page||'home';
if(header){const home=page==='home';header.innerHTML=`<a class="site-logo" href="${home?'#top':'index.html'}" aria-label="UAAD home"><img src="UAAD-WHITE.svg" alt="UAAD"></a><nav class="site-nav" aria-label="Primary"><a href="program.html" ${page==='program'||page==='program-item'?'aria-current="page"':''}>Programs</a><a href="stories.html" ${page==='stories'||page==='article'?'aria-current="page"':''}>Stories</a><a href="collaboration.html" ${page==='collaboration'?'aria-current="page"':''}>Collaboration</a><a href="about.html" ${page==='about'?'aria-current="page"':''}>About</a></nav><input class="site-search" id="search" type="search" placeholder="⌕  Search ${home?'projects':page==='program'||page==='program-item'?'programs':'stories'}" aria-label="Search ${home?'projects':page==='program'||page==='program-item'?'programs':'stories'}">`;
if(page==='article'||page==='program-item'){const search=header.querySelector('#search');search.addEventListener('keydown',e=>{if(e.key==='Enter'&&search.value.trim())location.href=(page==='article'?'stories.html':'program.html')+'?q='+encodeURIComponent(search.value.trim())})}
let previous=window.scrollY;window.addEventListener('scroll',()=>{const y=window.scrollY;if(y<90||y<previous-4)header.classList.remove('is-hidden');else if(y>previous+4)header.classList.add('is-hidden');previous=y},{passive:true});}
if(footer){footer.innerHTML=`<video class="site-footer-video" muted loop playsinline preload="metadata" aria-hidden="true"><source src="background.mp4" type="video/mp4"></video><div class="site-footer-main"><div class="site-footer-title">Underground<br>Art And Design</div><div class="site-footer-contact"><a href="mailto:hello@uaad.art">HELLO@UAAD.ART</a><div class="site-footer-social"><a href="https://www.instagram.com/uaad.art/" target="_blank" rel="noopener noreferrer">[INSTAGRAM]</a><a href="https://www.youtube.com/channel/UClT5QT-y-EUanu3h0TiiTcA" target="_blank" rel="noopener noreferrer">[YOUTUBE]</a><a href="https://www.linkedin.com/company/underground-art-and-design-llc" target="_blank" rel="noopener noreferrer">[LINKEDIN]</a></div></div></div><div class="site-footer-bottom"><a href="https://www.uaad.art/privacy" target="_blank" rel="noopener noreferrer">PRIVACY POLICY</a><span>TERMS AND CONDITIONS</span><span>© 2026 BY UNDERGROUND ART AND DESIGN</span></div>`;
const video=footer.querySelector('video');if('IntersectionObserver'in window)new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){const p=video.play();if(p)p.catch(()=>{})}else video.pause()}),{threshold:.01}).observe(video);}
})();
